repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
    - id: isort
      additional_dependencies: [toml]
  - repo: https://github.com/psf/black
    rev: 21.4b0
    hooks:
    - id: black
      language_version: python3.8
      args: [--line-length=100]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    - id: mypy
      files: tbd_example/
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
    - id: flake8
      additional_dependencies: [flake8-print]
      args: [--max-line-length=100, --ignore=E231]
